spring.application.name=Repaso6Note
# PostgreSQL Connection Details
spring.datasource.url=jdbc:postgresql://localhost:5432/proyecto1gestionnotas
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
